spring.application.name=employee


server.port=2020

# RDS MySQL
spring.datasource.url=jdbc:mysql://test-db.cvssa0y4ouh0.ap-south-1.rds.amazonaws.com:3306/test
spring.datasource.username=admin
spring.datasource.password=javaExpert1!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true